version: "3.8"

services:
  hamburg_academy_postgres:
    container_name: cybernet_postgres_prod
    image: "postgres:latest"
    environment:
      POSTGRES_DB: shedlock
      POSTGRES_USER: shedlock_cyber
      POSTGRES_PASSWORD: shedlock453
    ports:
      - "5433:5432"
    volumes:
      - cybernet_postgres_data_prod:/var/lib/postgresql/data

volumes:
  cybernet_postgres_data_prod:
